-- 깨진 아이콘 이모지를 원래 값으로 복구
update schedule_items set icon = '🛬' from schedule_days sd where schedule_items.day_id = sd.id and sd.key = 'd1' and schedule_items.title = 'LAX 도착';
update schedule_items set icon = '🍔' from schedule_days sd where schedule_items.day_id = sd.id and sd.key = 'd1' and schedule_items.title = 'In-N-Out 점심';
update schedule_items set icon = '🏨' from schedule_days sd where schedule_items.day_id = sd.id and sd.key = 'd1' and schedule_items.title = 'Aventura Hotel 체크인';
update schedule_items set icon = '🌊' from schedule_days sd where schedule_items.day_id = sd.id and sd.key = 'd1' and schedule_items.title = 'Venice Beach';
update schedule_items set icon = '🎡' from schedule_days sd where schedule_items.day_id = sd.id and sd.key = 'd1' and schedule_items.title = 'Santa Monica Pier';
update schedule_items set icon = '🥩' from schedule_days sd where schedule_items.day_id = sd.id and sd.key = 'd1' and schedule_items.title = 'Meat On Ocean (생일 저녁)';
update schedule_items set icon = '☕' from schedule_days sd where schedule_items.day_id = sd.id and sd.key = 'd2' and schedule_items.title = '브런치';
update schedule_items set icon = '💗' from schedule_days sd where schedule_items.day_id = sd.id and sd.key = 'd2' and schedule_items.title = 'Pink Wall';
update schedule_items set icon = '🛍️' from schedule_days sd where schedule_items.day_id = sd.id and sd.key = 'd2' and schedule_items.title = 'Madhappy + Aritzia';
update schedule_items set icon = '🏙️' from schedule_days sd where schedule_items.day_id = sd.id and sd.key = 'd2' and schedule_items.title = 'Beverly Hills';
update schedule_items set icon = '🛍️' from schedule_days sd where schedule_items.day_id = sd.id and sd.key = 'd2' and schedule_items.title = 'Rodeo Drive + Alo Yoga';
update schedule_items set icon = '🥤' from schedule_days sd where schedule_items.day_id = sd.id and sd.key = 'd2' and schedule_items.title = 'Erewhon 스무디';
update schedule_items set icon = '🎬' from schedule_days sd where schedule_items.day_id = sd.id and sd.key = 'd2' and schedule_items.title = 'Hollywood';
update schedule_items set icon = '🌇' from schedule_days sd where schedule_items.day_id = sd.id and sd.key = 'd2' and schedule_items.title = 'Griffith Observatory';
update schedule_items set icon = '🍩' from schedule_days sd where schedule_items.day_id = sd.id and sd.key = 'd3' and schedule_items.title = 'CityWalk 아침';
update schedule_items set icon = '🎮' from schedule_days sd where schedule_items.day_id = sd.id and sd.key = 'd3' and schedule_items.title = 'Super Nintendo World';
update schedule_items set icon = '🎥' from schedule_days sd where schedule_items.day_id = sd.id and sd.key = 'd3' and schedule_items.title = 'Studio Tour';
update schedule_items set icon = '🪄' from schedule_days sd where schedule_items.day_id = sd.id and sd.key = 'd3' and schedule_items.title = '해리포터 월드';
update schedule_items set icon = '🌃' from schedule_days sd where schedule_items.day_id = sd.id and sd.key = 'd3' and schedule_items.title = '저녁';
update schedule_items set icon = '🚗' from schedule_days sd where schedule_items.day_id = sd.id and sd.key = 'd4' and schedule_items.title = 'LA 출발';
update schedule_items set icon = '🍔' from schedule_days sd where schedule_items.day_id = sd.id and sd.key = 'd4' and schedule_items.title = 'Seligman 점심';
update schedule_items set icon = '🏨' from schedule_days sd where schedule_items.day_id = sd.id and sd.key = 'd4' and schedule_items.title = 'Kachina Lodge 체크인';
update schedule_items set icon = '🌅' from schedule_days sd where schedule_items.day_id = sd.id and sd.key = 'd4' and schedule_items.title = '일몰 감상';
update schedule_items set icon = '🥩' from schedule_days sd where schedule_items.day_id = sd.id and sd.key = 'd4' and schedule_items.title = 'El Tovar 저녁';
update schedule_items set icon = '🌅' from schedule_days sd where schedule_items.day_id = sd.id and sd.key = 'd5' and schedule_items.title = '그랜드캐년 일출';
update schedule_items set icon = '🍳' from schedule_days sd where schedule_items.day_id = sd.id and sd.key = 'd5' and schedule_items.title = 'Harvey House 아침';
update schedule_items set icon = '🚗' from schedule_days sd where schedule_items.day_id = sd.id and sd.key = 'd5' and schedule_items.title = 'Page 방향 출발';
update schedule_items set icon = '📸' from schedule_days sd where schedule_items.day_id = sd.id and sd.key = 'd5' and schedule_items.title = 'Antelope Canyon 투어 집결';
update schedule_items set icon = '🍽️' from schedule_days sd where schedule_items.day_id = sd.id and sd.key = 'd5' and schedule_items.title = '점심(브런치겸)';
update schedule_items set icon = '🌉' from schedule_days sd where schedule_items.day_id = sd.id and sd.key = 'd5' and schedule_items.title = 'Horseshoe Bend';
update schedule_items set icon = '🌆' from schedule_days sd where schedule_items.day_id = sd.id and sd.key = 'd5' and schedule_items.title = 'Flagstaff 이동&저녁';
update schedule_items set icon = '🚗' from schedule_days sd where schedule_items.day_id = sd.id and sd.key = 'd6' and schedule_items.title = 'Flagstaff 출발';
update schedule_items set icon = '🔔' from schedule_days sd where schedule_items.day_id = sd.id and sd.key = 'd6' and schedule_items.title = 'Bell Rock';
update schedule_items set icon = '🛬' from schedule_days sd where schedule_items.day_id = sd.id and sd.key = 'd6' and schedule_items.title = 'Airport Mesa';
update schedule_items set icon = '🛍️' from schedule_days sd where schedule_items.day_id = sd.id and sd.key = 'd6' and schedule_items.title = 'Tlaquepaque';
update schedule_items set icon = '🚗' from schedule_days sd where schedule_items.day_id = sd.id and sd.key = 'd6' and schedule_items.title = 'Phoenix로 출발';
update schedule_items set icon = '🏠' from schedule_days sd where schedule_items.day_id = sd.id and sd.key = 'd6' and schedule_items.title = 'Airbnb 체크인';
update schedule_items set icon = '🥩' from schedule_days sd where schedule_items.day_id = sd.id and sd.key = 'd6' and schedule_items.title = '법인장님 저녁';
update schedule_items set icon = '🌵' from schedule_days sd where schedule_items.day_id = sd.id and sd.key = 'd7' and schedule_items.title = 'Desert Botanical Garden';
update schedule_items set icon = '🎣' from schedule_days sd where schedule_items.day_id = sd.id and sd.key = 'd7' and schedule_items.title = 'Bass Pro Shops';
update schedule_items set icon = '🛍️' from schedule_days sd where schedule_items.day_id = sd.id and sd.key = 'd7' and schedule_items.title = 'Fashion Square';
update schedule_items set icon = '🏙️' from schedule_days sd where schedule_items.day_id = sd.id and sd.key = 'd7' and schedule_items.title = 'Old Town Scottsdale';
update schedule_items set icon = '🎯' from schedule_days sd where schedule_items.day_id = sd.id and sd.key = 'd7' and schedule_items.title = 'Target';
update schedule_items set icon = '🛒' from schedule_days sd where schedule_items.day_id = sd.id and sd.key = 'd7' and schedule_items.title = 'Trader Joe''s';
update schedule_items set icon = '🍔' from schedule_days sd where schedule_items.day_id = sd.id and sd.key = 'd7' and schedule_items.title = '저녁 자유시간';
update schedule_items set icon = '🧳' from schedule_days sd where schedule_items.day_id = sd.id and sd.key = 'd8' and schedule_items.title = '숙소 출발';
update schedule_items set icon = '🚙' from schedule_days sd where schedule_items.day_id = sd.id and sd.key = 'd8' and schedule_items.title = '렌터카 반납';
update schedule_items set icon = '✈️' from schedule_days sd where schedule_items.day_id = sd.id and sd.key = 'd8' and schedule_items.title = 'PHX 출발';
